version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: sbd-mongo
    ports:
      - "27017:27017"
    volumes:
      - sbd_mongo_db:/data/db
      - sbd_mongo_configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: unless-stopped
    networks:
      - sbd_internal

  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: sbd-elasticsearch
    ports:
      - "9200:9200"
    environment:
      - node.name=sbd-es01
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=password
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped
    networks:
      - sbd_internal

networks:
  sbd_internal:
    driver: 'bridge'

volumes:
  sbd_mongo_db:
  sbd_mongo_configdb: